# .github/workflows/generate_site_data.yml (本番用)
name: Generate Site Data

on:
  push:
    branches:
      - main # あなたのメインブランチ名に合わせてください
    paths-ignore:
      - 'update-info.json'
      - 'profile-data.json'
      - 'index.html' 
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    # リポジトリ変数 GH_USERNAME は、ステップ内の env で直接参照します
    # env:
    #   TARGET_GH_USERNAME: ${{ vars.GH_USERNAME }} # ジョブレベルで定義する必要は必ずしもありません

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests

      - name: Generate update-info.json
        run: |
          echo "{\"lastUpdated\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > update-info.json
          echo "Generated update-info.json:"
          cat update-info.json

      - name: Generate profile-data.json
        env:
          # リポジトリ変数 GH_USERNAME を Python スクリプトに渡す
          TARGET_GH_USERNAME_FROM_WORKFLOW: ${{ vars.GH_USERNAME }}
          # GitHub Actionsが提供する GITHUB_TOKEN を Python スクリプトに渡す
          GH_TOKEN_FROM_WORKFLOW: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "--- Running get_profile.py to generate profile-data.json ---"
          python scripts/get_profile.py # scripts/get_profile.py を実行

      - name: Fill HTML template to generate index.html
        run: |
          echo "--- Running fill_template.py to generate index.html ---"
          python scripts/fill_template.py # scripts/fill_template.py を実行
          echo "Generated index.html from template."

      - name: Commit and push if files changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          files_to_commit=""
          if [ -f update-info.json ]; then files_to_commit="$files_to_commit update-info.json"; fi
          if [ -f profile-data.json ]; then files_to_commit="$files_to_commit profile-data.json"; fi
          if [ -f index.html ]; then files_to_commit="$files_to_commit index.html"; fi
          
          if [ -n "$files_to_commit" ]; then
            echo "Files to commit: $files_to_commit"
            git add $files_to_commit
            if git diff --staged --quiet; then
              echo "No changes to generated files."
            else
              # コミットメッセージを index.html の更新も含むように修正
              git commit -m "Automated: Update site data and index.html" 
              git push
              echo "Updated generated files have been pushed to the repository."
            fi
          else
            echo "No files were generated or found to commit."
          fi
