# .github/workflows/generate_site_data.yml
name: Generate Site Data

on:
  push:
    branches:
      - main # あなたのメインブランチ名に合わせてください
    paths-ignore:
      - 'update-info.json'
      - 'profile-data.json'
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests

      - name: Generate update-info.json
        run: |
          echo "{\"lastUpdated\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > update-info.json
          echo "Generated update-info.json:"
          cat update-info.json

      - name: Generate profile-data.json
        env:
          # リポジトリ変数 GH_USERNAME をPythonスクリプトに渡すための環境変数として設定
          TARGET_GH_USERNAME_FROM_WORKFLOW: ${{ vars.GH_USERNAME }}
          # GitHub Actionsが提供する GITHUB_TOKEN をPythonスクリプトに渡す
          GH_TOKEN_FROM_WORKFLOW: ${{ secrets.GITHUB_TOKEN }}
        # Pythonスクリプトのパスを指定 (リポジトリのルートに scripts/get_profile.py があると仮定)
        run: |
          python scripts/get_profile.py

      - name: Commit and push if files changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          
          files_to_commit=""
          if [ -f update-info.json ]; then files_to_commit="$files_to_commit update-info.json"; fi
          if [ -f profile-data.json ]; then files_to_commit="$files_to_commit profile-data.json"; fi
          
          if [ -n "$files_to_commit" ]; then
            echo "Files to commit: $files_to_commit"
            git add $files_to_commit
            if git diff --staged --quiet; then
              echo "No changes to JSON data files."
            else
              git commit -m "Automated: Update site data (JSON files)"
              git push
              echo "Updated JSON data files have been pushed to the repository."
            fi
          else
            echo "No JSON data files were generated or found to commit."
          fi
